let trips = [
  { date: '6/12', week: 'FRI', label: 'DAY 01 · FRI, JUN 12', title: 'Arrive in Tokyo, ease into the city', weather: '☀ 25°C', items: [
    ['10:25', 'transport', '✈', 'ANA NH920 · Shanghai → Tokyo Haneda', 'Economy · 10:25–14:20 · Non-stop best match', '¥1,560'],
    ['15:30', 'stay', '⌂', 'Check in: The Gate Hotel Kaminarimon', 'Asakusa · 4.6 rating · 4-min walk to Senso-ji', '¥740'],
    ['17:00', 'sight', '◉', 'Senso-ji & Nakamise Street', 'A quieter time for photos, snacks, and wandering', 'Free'],
    ['19:00', 'food', '♨', 'Dinner: Asakusa Imahan · Sukiyaki', '4.5 rating · Guide favorite · Reserve ahead', '¥420']
  ]},
  { date: '6/13', week: 'SAT', label: 'DAY 02 · SAT, JUN 13', title: 'Market mornings and Ginza at night', weather: '☁ 24°C', items: [
    ['08:30', 'food', '☕', 'Breakfast: Le Pain de Joël Robuchon', 'Shinjuku Odakyu · 4.4 rating · Easy takeaway', '¥85'],
    ['10:30', 'sight', '◉', 'teamLab Borderless', 'Immersive digital art · Timed entry recommended', '¥280'],
    ['13:30', 'food', '♨', 'Lunch: Tsukiji Itadori', 'Seafood rice bowl · 4.3 rating', '¥160'],
    ['18:30', 'sight', '◉', 'An evening walk through Ginza', 'Walk from Hibiya Park to Ginza 4-chome', 'Free']
  ]},
  { date: '6/14', week: 'SUN', label: 'DAY 03 · SUN, JUN 14', title: 'The slower side of Daikanyama & Shibuya', weather: '☀ 26°C', items: [
    ['10:00', 'sight', '◉', 'Daikanyama T-Site', 'Books, design and coffee · Allow 90 minutes', 'Free'],
    ['12:30', 'food', '♨', 'Lunch: IVY PLACE', 'A Daikanyama brunch favorite · 4.4 rating', '¥180'],
    ['16:00', 'sight', '◉', 'Shibuya Sky', 'Enter before sunset for a day-to-night view', '¥170']
  ]},
  { date: '6/15', week: 'MON', label: 'DAY 04 · MON, JUN 15', title: 'Ueno art and an izakaya evening', weather: '☂ 22°C', items: [
    ['10:00', 'sight', '◉', 'Tokyo National Museum', 'Japanese Gallery and Asian Gallery · Allow 2.5 hours', '¥50'],
    ['13:30', 'food', '♨', 'Lunch: Izuei Honten', 'A century-old unagi restaurant · 4.2 rating', '¥260'],
    ['19:00', 'food', '♨', 'Dinner: Shinbashi Izakaya Alley', 'An after-work Tokyo classic', '¥230']
  ]},
  { date: '6/16', week: 'TUE', label: 'DAY 05 · TUE, JUN 16', title: 'One last coffee, then home', weather: '☀ 24°C', items: [
    ['09:30', 'food', '☕', 'Breakfast: Fuglen Asakusa', 'Nordic coffee and a final walk around Asakusa', '¥60'],
    ['12:00', 'transport', '✈', 'ANA NH919 · Tokyo Haneda → Shanghai', 'Economy · 12:00–14:15 · Non-stop best match', '¥1,560']
  ]}
];
const recs = [
  ['🍜', 'Fūunji Ramen', 'Shinjuku · Rich chicken ramen', '★ 4.4 · 1,900+ reviews'],
  ['🌿', 'Nezu Museum', 'Omotesando · Garden and art collection', '★ 4.5 · Traveler favorite'],
  ['🍡', 'Kōrakuen Tea House', 'Asakusa · Matcha and wagashi', '★ 4.6 · Avoid weekend queues']
];
let activeDay = 0;
const $ = s => document.querySelector(s);
let currentTripContext={destination:'Tokyo, Japan',dates:'2026-06-12 — 2026-06-16',origin:'',travelers:2};
function cleanPlaceName(name){return String(name).replace(/^(Check in:|Must-visit:|Dinner:|Lunch:|Breakfast:)\s*/,'')}
function reviewSearchUrl(name){return `https://www.google.com/search?q=${encodeURIComponent(`${cleanPlaceName(name)} ${currentTripContext.destination} reviews`)}`}
function ensureBookingCard(){if($('#booking-card'))return;const card=document.createElement('div');card.id='booking-card';card.className='booking-card';card.innerHTML=`<div class="card-title"><span>Ready when you are</span><span>↗</span></div><p>Compare live options before you book.</p><a id="flight-search" class="booking-link" target="_blank" rel="noopener">Search flights</a><a id="stay-search" class="booking-link booking-stay" target="_blank" rel="noopener">Find stays</a><small>Prices and availability are shown by the booking partner.</small>`;$('.side-panel').insertBefore(card,$('.recommend-card'))}
function renderBookingLinks(){ensureBookingCard();const range=String(currentTripContext.dates).match(/\d{4}-\d{2}-\d{2}/g)||[];const flightTerms=`${currentTripContext.origin?`${currentTripContext.origin} to `:''}${currentTripContext.destination} ${range.join(' ')}`;$('#flight-search').href=`https://www.google.com/travel/flights?q=${encodeURIComponent(flightTerms)}`;const booking=new URL('https://www.booking.com/searchresults.html');booking.searchParams.set('ss',currentTripContext.destination);if(range[0])booking.searchParams.set('checkin',range[0]);if(range[1])booking.searchParams.set('checkout',range[1]);booking.searchParams.set('group_adults',String(currentTripContext.travelers||2));booking.searchParams.set('no_rooms','1');booking.searchParams.set('group_children','0');$('#stay-search').href=booking.toString()}
function selectedTripDates(range){const values=String(range||'').match(/\d{4}-\d{2}-\d{2}/g)||[];if(values.length<2)return[];const start=new Date(`${values[0]}T12:00:00Z`),end=new Date(`${values[1]}T12:00:00Z`),count=Math.floor((end-start)/86400000)+1;if(!Number.isFinite(count)||count<1||count>21)return[];return Array.from({length:count},(_,i)=>new Date(start.getTime()+i*86400000))}
function buildDemoTimeline(range,city,style){const dates=selectedTripDates(range);if(!dates.length)return trips;return dates.map((date,index)=>{const first=index===0,last=index===dates.length-1;const day=String(index+1).padStart(2,'0');const short=new Intl.DateTimeFormat('en-US',{month:'numeric',day:'numeric',timeZone:'UTC'}).format(date);const week=new Intl.DateTimeFormat('en-US',{weekday:'short',timeZone:'UTC'}).format(date).toUpperCase();const long=new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric',timeZone:'UTC'}).format(date).toUpperCase();const title=first?`Welcome to ${city}`:last?`A final easy day in ${city}`:style==='food'?`A food-first day in ${city}`:style==='recharge'?`A slower day in ${city}`:`Discover ${city} at your own pace`;const items=first?[['15:00','stay','⌂','Check in to your stay','Add your confirmed hotel, homestay, or hostel here.','Set actual cost'],['16:30','transport','↔','Getting around: Metro or taxi','Use local transit for longer hops; take a taxi with luggage.','15–30 min'],['18:00','sight','◉',`First walk around ${city}`,'A flexible welcome stroll near your stay.','Flexible'],['20:00','food','♨','Dinner nearby','Choose a restaurant from the recommendations.','Set actual cost']]:last?[['09:30','food','♨','Breakfast nearby','A relaxed final meal before checkout.','Set actual cost'],['11:00','sight','◉','One last favorite stop','Keep this flexible for shopping, coffee, or a short walk.','Flexible'],['14:00','transport','↔','Leave for your next stop','Allow extra time for luggage and traffic.','30–60 min']]:[['10:00','sight','◉',`Explore ${city}`,'Add a recommended attraction or your own priority stop.','Flexible'],['12:30','food','♨','Lunch nearby','Choose a restaurant from the recommendations.','Set actual cost'],['14:00','transport','↔','Walk + local transit','Use the metro or bus for longer hops.','10–25 min'],['16:00','sight','◉','Free time nearby','Keep room for discoveries and rest.','Flexible']];return{date:short,week,label:`DAY ${day} · ${long}`,title,weather:'✦ Explore',items}})}
const demoHighlights={hangzhou:['West Lake','Lingyin Temple','Hefang Street','China National Tea Museum'],tokyo:['Senso-ji Temple','Meiji Jingu','Shibuya Crossing','Ueno Park'],kyoto:['Fushimi Inari Taisha','Kiyomizu-dera','Arashiyama Bamboo Grove','Nishiki Market'],shanghai:['The Bund','Yu Garden','Tianzifang','Shanghai Museum'],beijing:['Forbidden City','Temple of Heaven','Summer Palace','798 Art District'],paris:['Louvre Museum','Eiffel Tower','Montmartre','Musée d’Orsay'],london:['British Museum','Tower of London','Borough Market','Tate Modern'],rome:['Colosseum','Trevi Fountain','Pantheon','Vatican Museums'],berlin:['Museum Island','Brandenburg Gate','East Side Gallery','Bode Museum'],newyork:['Central Park','The Metropolitan Museum of Art','High Line','Brooklyn Bridge'],'new york':['Central Park','The Metropolitan Museum of Art','High Line','Brooklyn Bridge']};
function demoSight(city,index){const key=String(city).toLowerCase().replace(/[^a-z\s]/g,'').trim();const sights=demoHighlights[key]||[`${city} historic district`,`${city} main museum`,`${city} waterfront`,`${city} old town`];return sights[index%sights.length]}
function buildDemoTimeline(range,city,style){const dates=selectedTripDates(range);if(!dates.length)return trips;return dates.map((date,index)=>{const first=index===0,last=index===dates.length-1;const day=String(index+1).padStart(2,'0');const short=new Intl.DateTimeFormat('en-US',{month:'numeric',day:'numeric',timeZone:'UTC'}).format(date);const week=new Intl.DateTimeFormat('en-US',{weekday:'short',timeZone:'UTC'}).format(date).toUpperCase();const long=new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric',timeZone:'UTC'}).format(date).toUpperCase();const primary=demoSight(city,index);const secondary=demoSight(city,index+1);const title=first?`Welcome to ${city}`:last?`A final easy day in ${city}`:style==='food'?`A food-first day in ${city}`:style==='recharge'?`A slower day in ${city}`:`Discover ${city} at your own pace`;const items=first?[['15:00','stay','⌂','Check in to your stay','Add your confirmed hotel, homestay, or hostel here.','Set actual cost'],['16:30','transport','↔','Metro or taxi to your first stop','Use local transit for longer hops; take a taxi with luggage.','15–30 min'],['18:00','sight','◉',primary,`A signature ${city} highlight. Check opening hours before visiting.`,'Open listing'],['20:00','food','♨',`Dinner near ${primary}`,'Choose a well-reviewed restaurant from the recommendations.','Set actual cost']]:last?[['09:30','food','♨',`Breakfast near ${primary}`,'A relaxed final meal before checkout.','Set actual cost'],['11:00','sight','◉',primary,`A final stop at one of ${city}'s popular sights.`,'Open listing'],['14:00','transport','↔','Leave for your next stop','Allow extra time for luggage and traffic.','30–60 min']]:[['10:00','sight','◉',primary,`A popular ${city} highlight selected for your itinerary.`,'Open listing'],['12:30','food','♨',`Lunch near ${primary}`,'Choose a well-reviewed restaurant from the recommendations.','Set actual cost'],['14:00','transport','↔',`Metro or bus to ${secondary}`,'Use local transit for longer hops.','10–25 min'],['16:00','sight','◉',secondary,`Another popular stop to round out your day in ${city}.`,'Open listing']];return{date:short,week,label:`DAY ${day} · ${long}`,title,weather:'✦ Explore',items}})}
function renderTabs(){ $('#day-tabs').innerHTML = trips.map((d,i)=>`<button class="day-tab ${i===activeDay?'active':''}" data-day="${i}">${d.date}<b>${d.week}</b></button>`).join(''); document.querySelectorAll('.day-tab').forEach(b=>b.onclick=()=>{activeDay=+b.dataset.day;render()}) }
function icon(type){return type==='transport'?'✈':type==='stay'?'⌂':type==='food'?'♨':'◉'}
function render(){const day=trips[activeDay];renderTabs();$('#date-label').textContent=day.label;$('#day-title').textContent=day.title;$('.weather').textContent=day.weather;$('#timeline').innerHTML=day.items.map(([time,type,symbol,title,detail,price,image])=>`<article class="item ${type}"><div class="time">${time}</div><div class="dot-line"><span class="dot">${symbol}</span></div><div class="event-card">${image?`<img class="place-photo" src="${image}" alt="${title}" />`:''}<div class="event-main"><div class="event-icon">${icon(type)}</div><div><h4>${title}${detail.includes('Guide')?'<span class="tag">Guide pick</span>':''}</h4><p>${detail}</p></div></div><div class="event-price">${price}</div></div></article>`).join('')}
function renderRecs(){ $('#recommendations').innerHTML=recs.map(r=>`<div class="rec">${r[4]?`<img class="rec-photo" src="${r[4]}" alt="${r[1]}" />`:`<span class="rec-icon">${r[0]}</span>`}<div><h4>${r[1]}</h4><p>${r[2]}</p><span class="rating">${r[3]}</span></div></div>`).join('') }
function render(){const day=trips[activeDay];renderTabs();$('#date-label').textContent=day.label;$('#day-title').textContent=day.title;$('.weather').textContent=day.weather;$('#timeline').innerHTML=day.items.map(([time,type,symbol,title,detail,price,image])=>`<article class="item ${type}"><div class="time">${time}</div><div class="dot-line"><span class="dot">${symbol}</span></div><div class="event-card">${image?`<img class="place-photo" src="${image}" alt="${title}" />`:''}<div class="event-main"><div class="event-icon">${icon(type)}</div><div><h4>${title}${detail.includes('Guide')?'<span class="tag">Guide pick</span>':''}</h4><p>${detail}</p>${['food','sight','stay'].includes(type)?`<a class="review-link" href="${reviewSearchUrl(title)}" target="_blank" rel="noopener">Check reviews ↗</a>`:''}</div></div><div class="event-price">${price}</div></div></article>`).join('')}
function renderRecs(){$('#recommendations').innerHTML=recs.map(r=>`<div class="rec">${r[4]?`<img class="rec-photo" src="${r[4]}" alt="${r[1]}" />`:`<span class="rec-icon">${r[0]}</span>`}<div><h4>${r[1]}</h4><p>${r[2]}</p><span class="rating">${r[3]}</span><a class="review-link" href="${reviewSearchUrl(r[1])}" target="_blank" rel="noopener">Check reviews ↗</a></div></div>`).join('')}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
$('#plan-button').onclick=async()=>{const button=$('#plan-button');const destination=$('#destination').value.trim()||'Tokyo, Japan';const dates=$('#dates').value;const budget=$('#budget').value;const mustVisit=$('#must-visit').value.trim();const travelStyle=$('#travel-style').value;const meta=window.wayfareTripMeta||{travelers:2,accommodation:'hotel'};button.disabled=true;button.textContent='Planning…';try{const response=await fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({destination,dates,budget,mustVisit,travelStyle,travelers:meta.travelers,accommodation:meta.accommodation})});if(!response.ok)throw new Error('Plan request failed');const plan=await response.json();if(plan.trips?.length){trips=plan.trips;activeDay=0;recs.splice(0,recs.length,...plan.recommendations);render();renderRecs()}$('#trip-name').textContent=plan.city+' Escape';$('#timeline-title').textContent=`${trips.length} Days in ${plan.city}`;$('.muted').textContent=`${dates} · ${meta.travelers} traveler${meta.travelers===1?'':'s'} · Est. ${plan.estimate||'your budget'}`;const alert=$('#price-alert');alert.hidden=!plan.priceAlert;alert.textContent=plan.priceAlert||'';toast(plan.source==='open'?'Your open-data travel plan is ready':'Showing the demo plan — open data is unavailable')}catch(error){const city=destination.split(',')[0];trips=buildDemoTimeline(dates,city,travelStyle);activeDay=0;render();$('#trip-name').textContent=city+' Escape';$('#timeline-title').textContent=`${trips.length} Days in ${city}`;$('.muted').textContent=`${dates} · ${meta.travelers} traveler${meta.travelers===1?'':'s'} · Est. ¥7,680`;toast('Demo plan shown — open data is temporarily unavailable')}finally{button.disabled=false;button.innerHTML='Build my trip <span>→</span>'}};
let selectedStyle='sightseeing';
document.addEventListener('click',event=>{if(!event.target.closest('#plan-button'))return;const meta=window.wayfareTripMeta||{};currentTripContext={destination:$('#destination').value.trim()||'Tokyo, Japan',dates:$('#dates').value,origin:meta.origin||'',travelers:meta.travelers||2};renderBookingLinks()});
function showOnboardingStep(step){document.querySelectorAll('.onboarding-step').forEach(el=>el.classList.toggle('active',+el.dataset.step===step))}
document.querySelectorAll('.onboarding-next').forEach(button=>button.onclick=()=>{if(!$('#welcome-destination').value.trim()||!$('#welcome-dates').value.trim()){toast('Please add a destination and travel dates');return}showOnboardingStep(+button.dataset.next)});
document.querySelectorAll('.back-link').forEach(button=>button.onclick=()=>showOnboardingStep(+button.dataset.back));
document.querySelectorAll('.style-option').forEach(option=>option.onclick=()=>{selectedStyle=option.dataset.style;document.querySelectorAll('.style-option').forEach(item=>item.classList.toggle('selected',item===option));const city=$('#welcome-destination').value.split(',')[0]||'Your destination';const busy=/\b(jun|jul|aug|dec|jan|feb)\b|-(06|07|08|12|01|02)-/i.test($('#welcome-dates').value);$('#preview-city').textContent=city;$('#preview-style').textContent={food:'A food-first escape',sightseeing:'A culture and sights escape',recharge:'A slow, restorative escape'}[selectedStyle];$('#onboarding-summary').textContent=busy?'Your dates fall in a popular travel period — flights and hotels may cost more, so booking early is a smart move.':'We’re putting together your travel rhythm.';showOnboardingStep(3)});
$('#create-trip').onclick=()=>{const prefs=window.wayfarePreferences?window.wayfarePreferences():{travelers:2,budget:4000,returnDate:'',accommodation:'hotel'};window.wayfareTripMeta=prefs;$('#destination').value=$('#welcome-destination').value.trim();$('#dates').value=`${$('#welcome-dates').value} — ${prefs.returnDate}`;$('#budget').value=prefs.budget*prefs.travelers;$('#must-visit').value=$('#welcome-must-visit').value.trim();$('#travel-style').value=selectedStyle;$('#onboarding').hidden=true;$('#app-shell').hidden=false;$('#plan-button').click()};
$('#add-item').onclick=()=>$('#modal').classList.add('open');$('#close-modal').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').classList.remove('open')};
$('#add-form').onsubmit=e=>{e.preventDefault();const time=$('#new-time').value, title=$('#new-title').value, place=$('#new-place').value||'Custom plan';trips[activeDay].items.push([time,'sight','◉',title,place,'—']);trips[activeDay].items.sort((a,b)=>a[0].localeCompare(b[0]));$('#modal').classList.remove('open');e.target.reset();render();toast(`Added to day ${activeDay+1}`)};
$('#save-btn').onclick=()=>toast('Trip saved');$('#share-btn').onclick=()=>toast('Share link copied');$('#refresh-recs').onclick=()=>{recs.unshift(recs.pop());renderRecs();toast('Recommendations refreshed')};render();renderRecs();window.wayfareTimeline={get activeDay(){return activeDay},get trips(){return trips},render,toast};
