(() => {
  const original = new WeakMap();
  const zh = {
    'A MORE THOUGHTFUL WAY TO TRAVEL':'更贴心的旅行方式','Where would you':'你想','love to go?':'去哪里？','We’ll shape the details around your kind of escape.':'我们会依照你的旅行方式，安排每一个细节。','Destination':'目的地','When are you travelling?':'出行日期','Anything you absolutely want to see?':'有没有一定要去的地方？','optional':'选填','Continue':'继续','What kind of trip':'这趟旅行，','are you craving?':'你最想要什么？','Your answer helps us decide how to spend your most valuable hours.':'你的选择会帮助我们安排最值得花时间的体验。','Food first':'美食优先','Local classics, markets, and memorable tables':'当地经典、市集与值得记住的一餐','Sightseeing':'观光探索','Landmarks, culture, and unmissable views':'地标、文化与不容错过的风景','Recharge':'放松疗愈','Slow mornings, nature, and room to breathe':'慢节奏早晨、自然与留白','← Back':'← 返回','Your trip is':'你的旅程','taking shape.':'正在成形。','Your destination':'你的目的地','Tailored to you':'为你量身打造','Create my timeline':'生成我的时间线','YOUR TRAVEL COPILOT':'你的旅行助手','Turn anywhere you want to go':'把任何想去的地方','into a trip you can live.':'变成真正能出发的旅程。','Share your destination, dates, and budget. We connect flights, stays, standout food, and the city’s most memorable corners into one thoughtful plan.':'告诉我们目的地、日期和预算；我们会把交通、住宿、美食与城市亮点整理成一份行程。','Where to?':'去哪里？','Travel dates':'旅行日期','Total budget':'总预算','Must-visit place':'必去地点','Must-visit':'必去地点','Priority stop':'优先地点','Priority stop · Open data lookup':'优先地点 · 开放数据查询','Build my trip':'生成行程','YOUR ITINERARY':'你的行程','↗ Share':'↗ 分享','♡ Save trip':'♡ 保存行程','Trip budget':'旅行预算','Booking budget':'机酒预算','On-trip spending':'旅途消费','Transport':'交通','Stays':'住宿','Experiences':'体验','Picked for you':'为你挑选','Inspired by travel guides and recent reviews':'参考旅行攻略和近期评价','Bookings':'预订','Choose what you need, then add the confirmed details back to your plan.':'选择需要的预订，确认后再写回行程。','✈ Flights':'✈ 机票','🚆 Trains':'🚆 火车票','⌂ Stays':'⌂ 住宿','+ Stay':'+ 添加住宿','+ Transport':'+ 添加交通','Booking opens in a new tab.':'将在新页面打开预订。','Trip tools':'旅行工具','Optional helpers for your group.':'需要时再打开的同行小工具。','Group picks':'同行投票','Vote on today’s stops':'给今天的地点投票','Travel checklist':'旅行清单','Keep the essentials together':'把出行必备事项放在一起','ADD TO TIMELINE':'添加到时间线','Add a new plan':'新增行程','Added by':'添加人','Activity icon':'活动图标','Time':'时间','Plan name':'活动名称','Place':'地点','Add to timeline':'添加到时间线','Check reviews ↗':'查看评价 ↗','Open live transit route ↗':'打开实时公交路线 ↗','LOCAL MOODBOARD':'本地灵感册','Landscape':'风景','Culture':'文化','Taste':'美食','Fresh visual inspiration for your itinerary.':'为你的行程带来新鲜灵感。','My trips':'我的行程','YOUR WAYFARE COLLECTION':'你的 Wayfare 行程库','Where will you go next?':'下一站想去哪里？','Keep every little escape in one place.':'把每一次小小出逃都收藏在这里。','＋ Plan a new trip':'＋ 规划新行程','↓ Export itinerary':'↓ 导出行程','Open':'打开','Duplicate':'复制','Delete':'删除','Flexible budget':'弹性预算','Travel crew':'同行伙伴','Everyone here can shape the itinerary.':'每个人都可以一起设计这份行程。','Live':'在线','Planning this trip':'正在规划这次旅行','Can edit itinerary':'可以编辑行程','＋ Invite a friend':'＋ 邀请好友','Share the invite link so friends can add ideas and edit the timeline.':'分享邀请链接，让好友添加想法并编辑时间线。','ADD A CO-PLANNER':'添加同行伙伴','Invite a friend':'邀请好友','Give each traveler their own tiny identity in the shared itinerary.':'为每位旅行者设置专属头像和颜色。','Text color':'文字颜色','Avatar style':'头像样式','Add to travel crew':'加入同行伙伴','↗ Copy invite link instead':'↗ 复制邀请链接','Trip tools':'旅行工具','OpenStreetMap listing':'OpenStreetMap 地点信息','TRIP PULSE':'行程提醒','Little things to keep moving':'让旅程顺利进行的小提醒','Price watch':'价格提醒','Your dates look flexible — keep an eye on prices.':'你的日期比较灵活，可以留意价格变化。','Pick a restaurant together':'一起选餐厅','Open Group picks to let the crew vote on dining choices.':'打开同行投票，让大家一起选择餐厅。','Stay confirmed':'住宿已确认','Accommodation still open':'住宿尚未确认','Your check-in and check-out are in the timeline.':'入住和退房已经加入时间线。','Save the final place under Bookings when you are ready.':'确认后，可以在预订区域保存最终住宿。','essentials completed':'项必备事项已完成'
  };
  Object.assign(zh, {'Departure date':'出发日期','Return date':'返回日期','Departure city':'出发城市','Used to prepare your flight search':'用于准备机票搜索','Travelers':'同行人数','Booking budget / person':'每人机酒预算','On-trip budget / person':'每人旅途消费预算','Food, activities, and small daily expenses':'餐饮、活动和日常小额支出','Currency':'货币','Where would you like to stay?':'你希望住在哪里？','Hotel':'酒店','Homestay':'民宿','Hostel':'青旅','e.g. Hangzhou, China':'例如：杭州，中国','e.g. West Lake':'例如：西湖','e.g. Berlin, Germany':'例如：柏林，德国','e.g. 4000':'例如：4000','e.g. 600':'例如：600','e.g. 2':'例如：2','Check live reviews':'查看实时评价','Group favorite':'同行最喜欢','Guide pick':'攻略推荐','Where should we eat?':'这次吃什么？','Vote on restaurant choices near your stay':'为住宿附近的餐厅投票','Voting as':'投票人','Add a custom vote':'添加自定义投票','＋ Add option':'＋ 添加选项','Demo votes are saved in this browser.':'投票结果保存在当前浏览器中。','Restaurant choices will appear after the itinerary is generated.':'生成行程后，这里会显示餐厅选项。','Custom picks':'自定义选项','No votes yet':'还没有投票','vote':'票','votes':'票','Travel checklist':'旅行清单','ready':'项已准备','Personal checklist saved in this browser.':'个人清单保存在当前浏览器中。','Confirm your hotel booking':'确认酒店预订','Confirm your homestay booking':'确认民宿预订','Confirm your hostel booking':'确认青旅预订','Save flight or train tickets':'保存机票或火车票','Check passport / visa requirements':'确认护照/签证要求','Pack charger and power bank':'准备充电器和充电宝','Check the weather before you leave':'出发前查看天气','Share the final timeline with the crew':'与同行伙伴分享最终行程','e.g. Sunset cruise or cooking class':'例如：日落游船或烹饪课','＋ Add to this day':'＋ 添加到今天','Add to this day':'添加到今天'});
  const placeNames = {'West Lake':'西湖','Lingyin Temple':'灵隐寺','Zhejiang Museum':'浙江省博物馆','China Academy of Art Museum':'中国美术学院美术馆','Hefang Street':'河坊街','China National Tea Museum':'中国茶叶博物馆','Leifeng Pagoda':'雷峰塔','Xixi Wetland Park':'西溪湿地公园','Senso-ji Temple':'浅草寺','Meiji Jingu':'明治神宫','Shibuya Crossing':'涩谷十字路口','Ueno Park':'上野公园','Tokyo National Museum':'东京国立博物馆','teamLab Borderless':'teamLab Borderless 数字艺术馆','The Bund':'外滩','Yu Garden':'豫园','Tianzifang':'田子坊','Shanghai Museum':'上海博物馆','Forbidden City':'故宫','Temple of Heaven':'天坛','Summer Palace':'颐和园','The British Museum':'大英博物馆','British Museum':'大英博物馆','Louvre Museum':'卢浮宫','Eiffel Tower':'埃菲尔铁塔','Central Park':'中央公园','The Metropolitan Museum of Art':'大都会艺术博物馆'};
  const cityNames = {'beijing':'北京','hangzhou':'杭州','shanghai':'上海','tokyo':'东京','berlin':'柏林','paris':'巴黎','london':'伦敦','new york':'纽约','seoul':'首尔'};
  const localizeCity = value => cityNames[String(value || '').trim().toLowerCase()] || placeNames[value] || value;
  const translate = value => {
    if (zh[value]) return zh[value];
    const normalized = String(value).replace(/\s+/g, ' ').trim();
    if (normalized === 'Anything you absolutely want to see?') return '有没有一定要去的地方？';
    if (normalized === 'Departure city') return '出发城市';
    if (normalized === 'Used to prepare your flight search') return '用于准备机票搜索';
    if (normalized === 'On-trip budget') return '旅途消费预算';
    if (normalized === 'On-trip budget / person') return '每人旅途消费预算';
    if (normalized === 'Booking budget / person') return '每人机酒预算';
    if (normalized === 'What kind of trip') return '这趟旅行，';
    if (normalized === 'are you craving?') return '你最想要什么？';
    if (normalized === 'Food first') return '美食优先';
    if (normalized === 'Local classics, markets, and memorable tables') return '当地经典、市集与值得记住的一餐';
    if (normalized === 'Sightseeing') return '观光探索';
    if (normalized === 'Landmarks, culture, and unmissable views') return '地标、文化与不容错过的风景';
    if (normalized === 'Recharge') return '放松疗愈';
    if (normalized === 'Slow mornings, nature, and room to breathe') return '慢节奏早晨、自然与留白';
    if (normalized === '← Back') return '← 返回';
    if (normalized === 'A food-first escape') return '美食优先之旅';
    if (normalized === 'A culture and sights escape') return '文化与观光之旅';
    if (normalized === 'A slow, restorative escape') return '慢节奏疗愈之旅';
    if (normalized === 'We’re putting together your travel rhythm.') return '我们正在为你安排旅行节奏。';
    if (normalized === 'Your dates fall in a popular travel period — flights and hotels may cost more, so booking early is a smart move.') return '你的出行日期处于热门旅行时段，机票和酒店可能更贵，建议尽早预订。';
    if (normalized === 'Build my trip') return '生成我的行程';
    if (normalized === 'Planning…') return '正在规划…';
    if (normalized === 'Create my timeline') return '生成我的时间线';
    if (normalized === 'Continue') return '继续';
    if (normalized === 'Must-visit place') return '必去地点';
    if (normalized === 'Must visit') return '必去地点';
    if (normalized === 'Must-visit') return '必去地点';
    if (normalized === 'Priority stop') return '优先地点';
    if (normalized === 'Priority stop · Open data lookup') return '优先地点 · 开放数据查询';
    if (placeNames[value]) return placeNames[value];
    let match = String(value).match(/^(\d+) Days in (.+)$/); if (match) return `${match[2]} · ${match[1]} 天`;
    match = String(value).match(/^Welcome to (.+)$/); if (match) return `欢迎来到 ${match[1]}`;
    match = String(value).match(/^A first taste of (.+)$/); if (match) return `${match[1]} · 初尝当地风味`;
    match = String(value).match(/^A gentle arrival in (.+)$/); if (match) return `${match[1]} · 轻松抵达`;
    match = String(value).match(/^A final easy day in (.+)$/); if (match) return `${match[1]} · 轻松收尾的一天`;
    match = String(value).match(/^A food-first day in (.+)$/); if (match) return `${match[1]} · 美食优先的一天`;
    match = String(value).match(/^Eat your way through (.+)$/); if (match) return `在 ${match[1]} 开启美食之旅`;
    match = String(value).match(/^A slower day in (.+)$/); if (match) return `${match[1]} · 慢节奏的一天`;
    match = String(value).match(/^A slower day in (.+)$/); if (match) return `${match[1]} · 慢节奏的一天`;
    match = String(value).match(/^A gentle arrival in (.+)$/); if (match) return `${match[1]} · 轻松抵达`;
    match = String(value).match(/^(.+), at your own pace$/); if (match) return `${match[1]} · 按自己的节奏探索`;
    match = String(value).match(/^Discover (.+) at your own pace$/); if (match) return `按自己的节奏探索 ${match[1]}`;
    match = String(value).match(/^A popular (.+) highlight selected for your itinerary\.$/); if (match) return `为你的行程挑选的热门${match[1]}景点。`;
    match = String(value).match(/^(Transport|Stays) ([¥$][\d,]+)$/); if (match) return `${match[1] === 'Transport' ? '交通' : '住宿'} ${match[2]}`;
    match = String(value).match(/^([¥$][\d,]+) above your flexible booking budget\.$/); if (match) return `${match[1]} 超过弹性机酒预算。`;
    match = String(value).match(/^([¥$][\d,]+) left in your booking budget\.$/); if (match) return `机酒预算还剩 ${match[1]}。`;
    match = String(value).match(/^([¥$][\d,]+) left for food and experiences\.$/); if (match) return `餐饮和体验还剩 ${match[1]}。`;
    match = String(value).match(/^([¥$][\d,]+) over your on-trip budget — adjust the plan or budget\.$/); if (match) return `${match[1]} 超过旅途消费预算，可以调整行程或预算。`;
    match = String(value).match(/^(FOOD|SIGHTSEEING|RECHARGE) ESCAPE$/); if (match) return `${({FOOD:'美食',SIGHTSEEING:'观光',RECHARGE:'放松'})[match[1]]}之旅`;
    match = String(value).match(/^(\d+)\/6 essentials completed$/); if (match) return `${match[1]}/6 项必备事项已完成`;
    match = String(value).match(/^(.+?) neighborhood café$/i); if (match) return `${localizeCity(match[1])} 社区咖啡馆`;
    match = String(value).match(/^(.+?) noodle shop$/i); if (match) return `${localizeCity(match[1])} 面馆`;
    match = String(value).match(/^(.+?) market counter$/i); if (match) return `${localizeCity(match[1])} 市集小摊`;
    match = String(value).match(/^(.+?) tea house$/i); if (match) return `${localizeCity(match[1])} 茶馆`;
    match = String(value).match(/^(.+?) dessert bar$/i); if (match) return `${localizeCity(match[1])} 甜品店`;
    match = String(value).match(/^(.+?) family-run restaurant$/i); if (match) return `${localizeCity(match[1])} 家庭餐馆`;
    match = String(value).match(/^(.+?) historic district$/i); if (match) return `${localizeCity(match[1])} 历史街区`;
    match = String(value).match(/^(.+?) main museum$/i); if (match) return `${localizeCity(match[1])} 城市博物馆`;
    match = String(value).match(/^(.+?) art gallery district$/i); if (match) return `${localizeCity(match[1])} 艺术街区`;
    match = String(value).match(/^(.+?) botanical garden$/i); if (match) return `${localizeCity(match[1])} 植物园`;
    match = String(value).match(/^(.+?) waterfront$/i); if (match) return `${localizeCity(match[1])} 滨水区`;
    match = String(value).match(/^(.+?) old town$/i); if (match) return `${localizeCity(match[1])} 老城区`;
    match = String(value).match(/^(.+?) market hall$/i); if (match) return `${localizeCity(match[1])} 市集大厅`;
    match = String(value).match(/^(.+?) city viewpoint$/i); if (match) return `${localizeCity(match[1])} 城市观景台`;
    match = String(value).match(/^(\d+)\/(\d+) ready$/i); if (match) return `${match[1]}/${match[2]} 项已准备`;
    match = String(value).match(/^(\d+) vote(?:s)?$/i); if (match) return `${match[1]} 票`;
    match = String(value).match(/^(.+) · A dining choice near your stay$/i); if (match) return `${localizeCity(match[1])} · 住宿附近的餐饮选择`;
    match = String(value).match(/^(.+) · Popular local highlight$/i); if (match) return `${localizeCity(match[1])} · 当地热门景点`;
    match = String(value).match(/^(.+) · Chosen near your stay$/i); if (match) return `${localizeCity(match[1])} · 根据住宿位置挑选`;
    match = String(value).match(/^(.+) · Open data$/); if (match) return `${match[1]} · 开放数据`;
    match = String(value).match(/^(.+) · A popular local highlight to consider\.$/); if (match) return `${match[1]} · 值得考虑的当地热门景点。`;
    match = String(value).match(/^(.+) · A low-pressure nearby stop$/); if (match) return `${match[1]} · 附近轻松无压力的停留点`;
    match = String(value).match(/^(.+) · A gentle stop near your stay$/); if (match) return `${match[1]} · 住宿附近的轻松停留`;
    match = String(value).match(/^(.+) · A signature (.+) highlight\.$/); if (match) return `${match[1]} · ${match[2]}的代表性景点。`;
    match = String(value).match(/^Explore (.+)$/); if (match) return `探索 ${match[1]}`;
    match = String(value).match(/^First walk around (.+)$/); if (match) return `在 ${match[1]} 初次漫步`;
    match = String(value).match(/^Dinner near (.+)$/); if (match) return `在 ${match[1]} 附近吃晚餐`;
    match = String(value).match(/^Lunch near (.+)$/); if (match) return `在 ${match[1]} 附近吃午餐`;
    match = String(value).match(/^Breakfast near (.+)$/); if (match) return `在 ${match[1]} 附近吃早餐`;
    match = String(value).match(/^Dinner nearby$/i); if (match) return '附近晚餐';
    match = String(value).match(/^Lunch nearby$/i); if (match) return '附近午餐';
    match = String(value).match(/^Breakfast nearby$/i); if (match) return '附近早餐';
    match = String(value).match(/^Leave for your next stop$/i); if (match) return '出发前往下一站';
    match = String(value).match(/^Metro or bus to (.+)$/); if (match) return `乘坐地铁或公交前往 ${match[1]}`;
    match = String(value).match(/^Another popular stop to round out your day in (.+)\.$/); if (match) return `在 ${match[1]} 的另一个热门地点结束这一天。`;
    match = String(value).match(/^A final stop at one of (.+)'s popular sights\.$/); if (match) return `${match[1]} 的热门景点收尾。`;
    match = String(value).match(/^A signature (.+) highlight\. Check opening hours before visiting\.$/); if (match) return `${match[1]} 的代表性景点，出发前请确认开放时间。`;
    match = String(value).match(/^(.+) · (\d+(?:\.\d+)?) km from (.+) · about (.+) min\..*$/); if (match) return `${match[1]} · 距离 ${match[3]} ${match[2]} 公里 · 约 ${match[4]} 分钟`;
    const sentences = {'Set actual cost':'填写实际花费','Open listing':'查看地点','Flexible':'弹性安排','Near your stay.':'住宿附近。','Check in to your stay':'入住住宿','Add your confirmed hotel, homestay, or hostel here.':'在这里添加已确认的酒店、民宿或青旅。','A relaxed final meal before checkout.':'退房前轻松吃最后一餐。','A final meal near your stay.':'住宿附近的最后一餐。','A casual first stop near your stay.':'抵达后在住宿附近轻松停留。','A well-reviewed option near your stay.':'住宿附近评价不错的选择。','A short, easy stop before departure.':'出发前轻松短暂停留。','Allow extra time for luggage, traffic, and the airport or station.':'为行李、交通以及机场或车站预留充足时间。','Allow extra time for luggage and traffic.':'为行李和交通预留充足时间。'};
    if (sentences[value]) return sentences[value];
    const prefixes = {'Breakfast:':'早餐：','Lunch:':'午餐：','Afternoon tea:':'下午茶：','Dinner:':'晚餐：','Welcome bite:':'抵达第一口：','Slow café:':'慢享咖啡：','Last local bite:':'最后一口当地风味：','A quiet pause:':'安静休息：','Check in:':'入住：','Check out:':'退房：','Must-visit:':'必去：','Open listing':'查看地点'};
    for (const [from,to] of Object.entries(prefixes)) if (String(value).toLowerCase().startsWith(from.toLowerCase())) { const rest=String(value).slice(from.length).trim(); return `${to}${translate(rest)}`; }
    match = String(value).match(/^Slow breakfast:\s*(.+)$/i); if (match) return `慢享早餐：${translate(match[1])}`;
    return String(value).replace(/^(\d+) travelers$/, '$1 位旅行者').replace(/^(.+) in little moments$/, '$1 的城市瞬间');
  };
  function textNodes(root = document.body) {
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, { acceptNode: node => node.parentElement && !['SCRIPT','STYLE'].includes(node.parentElement.tagName) && node.nodeValue.trim() ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT });
    const nodes=[]; while(walker.nextNode()) nodes.push(walker.currentNode); return nodes;
  }
  function apply() {
    const locale = window.wayfareLocale || 'en'; document.documentElement.lang = locale === 'zh' ? 'zh-CN' : 'en';
    textNodes().forEach(node => { if (!original.has(node)) original.set(node,node.nodeValue); const source=original.get(node); const next=locale === 'zh' ? translate(source) : source; if (node.nodeValue !== next) node.nodeValue=next; });
    document.querySelectorAll('input[placeholder]').forEach(input => { if (!input.dataset.enPlaceholder) input.dataset.enPlaceholder=input.placeholder; input.placeholder=locale === 'zh' ? translate(input.dataset.enPlaceholder) : input.dataset.enPlaceholder; });
    document.querySelectorAll('[data-language-toggle]').forEach(button => { const next=locale === 'zh' ? 'EN' : '中文'; if (button.textContent !== next) button.textContent=next; });
  }
  function toggle() { window.wayfareLocale=window.wayfareLocale === 'zh' ? 'en' : 'zh'; localStorage.setItem('wayfare-locale',window.wayfareLocale); apply(); }
  window.wayfareLocale=localStorage.getItem('wayfare-locale') || 'en'; document.querySelectorAll('[data-language-toggle]').forEach(button => button.onclick=toggle); new MutationObserver(() => { if (window.wayfareLocale === 'zh') apply(); }).observe(document.body,{childList:true,subtree:true,characterData:true}); apply();
})();
